### ISSUE TITLE
Using with react-three-fiber

### ISSUE THREAD

**Issue by FettahAud** [Fyrestar/THREE.extendMaterial#19]
I am trying to use it with R3F but got this error even in the console I'm getting  the class. 

Any suggestions??

![image](https://user-images.githubusercontent.com/74654437/213811818-7faff23d-47c1-431b-961e-2132404341c8.png)

**Comment by PerryRylance** [comment]
This is a result of the way this library tries to interact with THREE rather than specifically to do with react-three-fibre

You'd need to either bring this libraries source into your own source and import the relevant THREE modules where they are used

I arrived here because I'm trying to extend a built in material and pass my own uniform (`time`) into the extended shader, I've not used this library just yet so I don't have source I can share, but happy to do that once I finish adapting it. I'll probably fork this repo once I figure it out, if that's helpful to you
